apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306        # Cluster port
      targetPort: 3306  # Container port
  type: ClusterIP
