apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-ns
spec:
  selector:
    app: nginx
    version: v1
  ports:
  - port: 80  #cluster/host
    targetPort: 80 #container port
    protocol: TCP
  type: NodePort
