version: "3.9"

networks:
  notes-net:   # yahan apna network define kar diya

services:
  db:
    image: mysql:8.0
    container_name: notes-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: notesdb
    volumes:
      - notes-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - notes-net   # db service ko network me joda
    restart: always

  backend:
    build: ./backend
    container_name: notes-backend
    environment:
      DB_HOST: db     # network ke andar "db" service name se resolve hoga
      DB_USER: root
      DB_PASS: rootpassword
      DB_NAME: notesdb
    depends_on:
      - db
    ports:
      - "3000:3000"   # optional, debugging ke liye
    networks:
      - notes-net     # backend bhi same network me
    restart: always

  frontend:
    image: nginx:latest
    container_name: notes-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - notes-net     # frontend bhi connect
    restart: always

volumes:
  notes-data:
